### ISSUE TITLE
Problems attribute-driven-cookbook and chef 12.5 - provider not found

### ISSUE THREAD

**Issue by jimdowling** [realityforge/chef-glassfish#57]
I have problems with "provider not found" for ubuntu 14.04 with chef 12.5+ - not 12.4 or less.
This is using the attribute driven cookbook, and installing the jdbc_resource. Sorry, I don't have a trace right now.

**Comment by jackcrews** [comment]
I have the same problem. It seems like with 12.5 it is loosing the provider name 'glassfish_jdbc_resource': Here is my output:
```
glassfish_jdbc_connection_pool[MySqlCPDS] action create
* bash[asadmin_create_jdbc_connection_pool MySqlCPDS] action run
  - execute "bash"  "/tmp/chef-script20151009-1498-1nyjtgd"

jdbc/WebarcDS[jdbc/WebarcDS] action create

================================================================================
Error executing action `create` on resource 'jdbc/WebarcDS[jdbc/WebarcDS]'
================================================================================

Chef::Exceptions::ProviderNotFound
----------------------------------
Cannot find a provider for jdbc/WebarcDS[jdbc/WebarcDS] on ubuntu version 14.04

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/glassfish/recipes/attribute_driven_domain.rb

614:       glassfish_jdbc_resource resource_name.to_s do
615:         domain_name domain_key
616:         admin_port admin_port if admin_port
617:         username username if username
618:         password_file password_file if password_file
619:         secure secure if secure
620:         system_user system_username if system_username
621:         system_group system_group if system_group
622:         connectionpoolid pool_name
623:         resource_configuration.each_pair do |config_key, value|
624:           self.send(config_key, value) unless config_key == 'priority'
625:         end
626:       end
627:     end
628:   end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/glassfish/recipes/attribute_driven_domain.rb:614:in `block (3 levels) in from_file'

jdbc/WebarcDS("jdbc/WebarcDS") do
  action [:create]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  system_user "glassfish"
  system_group "glassfish-admin"
  declared_type :glassfish_jdbc_resource
  cookbook_name "glassfish"
  recipe_name "attribute_driven_domain"
  domain_name "xxxxx"
  admin_port 4848
  username "admin"
  password_file "/srv/glassfish/stxxxx_admin_passwd"
  connectionpoolid "MySqlCPDS"
  description "Resource for xxx Pool"
end
```

**Comment by realityforge** [comment]
This seems to be a duplicate of #50 - Unfortunately we are still on an earlier version of chef so have not been able to investigate

**Comment by realityforge** [comment]
I believe this is fixed by https://github.com/realityforge/chef-glassfish/commit/865cc0126d6618eefbc65858ae86e0bee7982363

**Comment by conoyes** [comment]
I still experience the issue. The problem disappears when this is present in `metadata.rb`:
`depends 'compat_resource'`

**Comment by realityforge** [comment]
@conoyes Can you explain the scenario where this still occurs for you? Are you using chef-server? Are you sure the cookbook is uploaded to chef-server before you converge the node? 

Trying to reproduce it ...

**Comment by conoyes** [comment]
@realityforge We don't use Chef Server right now. The way we use Chef is through chef-solo runs with pre-assembled node.json files and pre-downloaded cookbook dependencies with librarian-chef. I experienced this issue during development with ChefDK 0.10.0 on OpenSuSE. We develop a wrapper cookbook around the glassfish cookbook with the `depends 'glassfish', '~> 0.7.4'` directive in the `metadata.rb` file. The issue is still present if I add `depends 'compat_resource'` as well. The problem disappears if I alter the glassfish cookbook's `metadata.rb` and add `depends 'compat_resource'`. Versions I use:
```
$ ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
$ chef-solo --version
Chef: 12.5.1
```
And the node.json file is something like this:
```
{
	"run_list": [
		"recipe[XXXXX::XXXXX]"
	]
}
```
Thanks :+1:

**Comment by realityforge** [comment]
Hmm .. it looks like that cookbook will never work in Chef 11 and earlier. See

https://github.com/chef-cookbooks/compat_resource/blob/master/files/lib/compat_resource.rb#L26

It does also seem the depends statement needs to be present. In the next week or two I will try and organize it so that there is a separate branch for chef 11 compatibility so we can move forward with chef 12 support

**Comment by conoyes** [comment]
Sounds good, thanks.
